version: "3.8"
services:
  backend:
    image: nivleking/blc-shipping-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./blc-shipping-backend:/var/www/html
      - ./blc-shipping-backend/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: blc_shipping
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network
    command: sh -c "/usr/local/bin/wait-for-it.sh && /usr/local/bin/init.sh"

  frontend:
    image: nivleking/blc-shipping-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend-blc-shipping:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  websocket:
    image: nivleking/blc-shipping-websocket:latest
    ports:
      - "6001:6001"
    volumes:
      - ./websockets-blc-shipping:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blc_shipping
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
#
